import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Navbar from "../../components/Navbar";
import HeroSection from "../../components/HeroSection";
import WeInvest from "../../components/WeInvest";
import ChooseUs from "../../components/ChooseUs";
import TrustedWorldwide from "../../components/TrustedWorldwide";
import Testimonials from "../../components/Testimonials";
import AddsOn from "../../components/AddsOn";
import Footer from "../../components/Footer";
import About from "../../components/About";
import OurFeatures from "../../components/OurFeatures";
import OurTeam from "../../components/OurTeam";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Holms Merchant Bank</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <HeroSection />
      <About />
      <WeInvest />
      <OurFeatures />
      <ChooseUs />
      <TrustedWorldwide />
      <Testimonials />
      <OurTeam />
      <AddsOn />
      <Footer />
    </>
  );
}
